### ISSUE TITLE
Not receiving subscribed channel event.

### ISSUE THREAD

**Issue by ShineRajat** [perrystreetsoftware/PSSRedisClient#1]
Hello Sir,
           I have downloaded PSSRedisClient project and run project after changing port and local host. Connection stablished message received. But after some time it is giving peer to peer to remote connection error. and also getting same error when we execute any command like PING or any other command.

**Comment by esilverberg** [comment]
Sounds like your redis-server may be disconnecting your client. That is a setting in redis.confi, check your timeout value.
