### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by mxw39** [perrystreetsoftware/PSSRedisClient#3]
Hi, 

Is support for SSL connection to Redis server, e.g. rediss://some-redis-server.com, on the roadmap for the near future?

**Comment by esilverberg** [comment]
Some form of tunneling would be required. You may be able to configure SSL with GCDAsyncSocket. 

https://redis.io/topics/encryption
https://stackoverflow.com/questions/18328465/gcdasyncsocket-with-ssl

**Comment by mxw39** [comment]
Thanks for the reply!
